In [1]:
import numpy as np
import pandas as pd
import sympy as sp

from utilities import SingleDetector

In [2]:
SLOPE_ANGLE = 3 * sp.pi / 360
DETECTOR_ANGLE = 2 * sp.pi / 3
DIRECTION_ANGLE = sp.pi/2
CENTER_WATER_DEPTH = 120

PRECISION = 20

NM_TO_M = 1852

In [3]:
# 创建一个 dataframe 用于存储数据
index = np.arange(0, 8)
angles = index * sp.pi / 4
columns = ['direction_angle', *np.arange(0.0, 2.4, 0.3)]
df = pd.DataFrame(index=index, columns=columns)
df['direction_angle'] = angles
df

,direction_angle,0.0,0.3,0.6,0.8999999999999999,1.2,1.5,1.7999999999999998,2.1
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,pi/4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,pi/2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3*pi/4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,pi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5*pi/4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,3*pi/2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7*pi/4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
for i in index:
    direction_angle = df['direction_angle'][i]
    # 根据方向角确认是上坡还是下坡 （-pi/2 ~ pi/2）为下坡，（pi/2 ~ 3pi/2）为上坡
    if direction_angle >= sp.pi/2 and direction_angle <= 3*sp.pi/2:
        flag = -1
    else:
        flag = 1

    # 获得相对坡度角度
    detector = SingleDetector(center_depth=CENTER_WATER_DEPTH, 
                              slope_angle=SLOPE_ANGLE,
                              detector_angle=DETECTOR_ANGLE,
                              direction_angle=direction_angle,
                              precision=PRECISION)
    detector.get_measuring_line()
    measuring_line_relative_slope = detector.measuring_slope_line_angle_xy

    # print(flag*measuring_line_relative_slope)

    for j in range(1, len(df.columns)):
        distance_from_center = df.columns[j] * NM_TO_M
        # print(distance_from_center)
        detector = SingleDetector(center_depth=CENTER_WATER_DEPTH +\
                                               distance_from_center*sp.tan(flag*measuring_line_relative_slope), 
                                  slope_angle=SLOPE_ANGLE,
                                  detector_angle=DETECTOR_ANGLE,
                                  direction_angle=direction_angle,
                                  precision=PRECISION)
        detector.get_scan_segment()
        df.iloc[i, j] = detector.scan_segment_length_proj_xy

df

,direction_angle,0.0,0.3,0.6,0.8999999999999999,1.2,1.5,1.7999999999999998,2.1
0,0,415.69219381653055044,466.09105495939007512,516.48991610224959980,566.88877724510909352,617.28763838796864914,667.68649953082816350,718.08536067368763660,768.48422181654723346
1,pi/4,416.12019579714518009,451.79426497234900640,487.46833414755283271,523.14240332275663710,558.81647249796048530,594.49054167316430430,630.16461084836809412,665.83868002357197153
2,pi/2,416.54908003873492616,416.54908003873492616,416.54908003873492616,416.54908003873492616,416.54908003873492616,416.54908003873492616,416.54908003873492616,416.54908003873492616
3,3*pi/4,416.12019579714518009,380.44612662194135378,344.77205744673752750,309.09798827153372307,273.42391909632987488,237.74984992112605587,202.07578074592226607,166.40171157071838866
4,pi,415.69219381653055044,365.29333267367102578,314.89447153081150110,264.49561038795200736,214.09674924509245176,163.69788810223293740,113.29902695937346429,62.900165816513867432
5,5*pi/4,416.12019579714518009,380.44612662194135378,344.77205744673752750,309.09798827153372307,273.42391909632987488,237.74984992112605587,202.07578074592226607,166.40171157071838866
6,3*pi/2,416.54908003873492616,416.54908003873492616,416.54908003873492616,416.54908003873492616,416.54908003873492616,416.54908003873492616,416.54908003873492616,416.54908003873492616
7,7*pi/4,416.12019579714518009,451.79426497234900640,487.46833414755283271,523.14240332275663710,558.81647249796048530,594.49054167316430430,630.16461084836809412,665.83868002357197153